baseURL = "https://inakenn5.github.io/overseas_reaction_blog-site/"
languageCode = "ja"
title = "海外の反応で見る日本人サッカー選手"

[params]
  description = "欧州で活躍する日本人サッカー選手に、海外のファンはどんな反応をしているんだろう？そんな声を日本語に訳してお届けします。"

[markup.goldmark.renderer]
  unsafe = true

[taxonomies]
  tag = "tags"
  category = "categories"

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]
